RazorPagesGeneral/Pages/Employees/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesLessons.Models;
using RazorPagesLessons.Services;

namespace RazorPagesGeneral.Pages.Employees
{
    public class DeleteModel : PageModel
    {
        private readonly IEmployeeRepository _employeeRepository;
        
        private readonly IWebHostEnvironment _webHostEnvironment;
       
        public DeleteModel(IEmployeeRepository employeeRepository, IWebHostEnvironment webHostEnvironment)
        {
            _employeeRepository = employeeRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        [BindProperty]
        public Employee Employee{ get; set; }

        public IActionResult OnGet(int id)
        {
            Employee = _employeeRepository.GetEmployee(id);

            if (Employee == null)
                return RedirectToPage("/Notfound");

            return Page();
        }

        public IActionResult OnPost()
        {
            Employee deletedEmployee = _employeeRepository.Delete(Employee.Id);
            
            if (deletedEmployee.PhotoPath != null)
            {
                string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", deletedEmployee.PhotoPath);

                if (deletedEmployee.PhotoPath != "noimage.png")
                {
                    System.IO.File.Delete(filePath);
                }
            }

            if (deletedEmployee == null)
                return RedirectToPage("/NotFound");
            return RedirectToPage("Employees");
        }


    }
}

RazorPagesGeneral/Pages/Employees/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesLessons.Models;
using RazorPagesLessons.Services;

namespace RazorPagesGeneral.Pages.Employees
{
    public class DetailsModel : PageModel
    {
        private readonly IEmployeeRepository _employeeRepository;
        public DetailsModel(IEmployeeRepository employeeRepository)
        {
            _employeeRepository = employeeRepository;
        }

        public Employee Employee { get; private set; }

        public void OnGet(int id)
        {
            Employee = _employeeRepository.GetEmployee(id);
        }
    }
}

RazorPagesGeneral/Pages/Employees/Edit.cshtml.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesLessons.Models;
using RazorPagesLessons.Services;

namespace RazorPagesGeneral.Pages.Employees
{
    public class EditModel : PageModel
    {
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public EditModel(IEmployeeRepository employeeRepository, IWebHostEnvironment webHostEnvironment)
        {
            _employeeRepository = employeeRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        [BindProperty]
        public Employee Employee { get; set; }

        [BindProperty]
        public IFormFile Photo { get; set; }
        
        [BindProperty]
        public bool Notify { get; set; }

        public string Massage { get; set; }



        public IActionResult OnGet(int? id)
        {
            if (id.HasValue)
                Employee = _employeeRepository.GetEmployee(id.Value);
            else
                Employee = new Employee();

            if (Employee == null)
                RedirectToPage("/NotFound");
            return Page();
        }

        public IActionResult OnPost()
        {
            if(ModelState.IsValid)
            {
                if(Photo!= null)
                {
                    if(Employee.PhotoPath != null)
                    {
                        string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", Employee.PhotoPath);

                        if (Employee.PhotoPath != "noimage.png")
                        {
                            System.IO.File.Delete(filePath);
                        }
                    }

                    Employee.PhotoPath = ProcessUploadFile();
                }

                if(Employee.Id>0)
                { 
                Employee = _employeeRepository.Update(Employee);

                TempData["SuccessMessage"] = $"Update {Employee.Name} Successful!"; 
                
                }
                else
                {
                    Employee = _employeeRepository.Add(Employee);

                    TempData["SuccessMessage"] = $"Adding {Employee.Name} Successful!";

                }

                return RedirectToPage("Employees");
               
            }
            
                return Page();

        }

        public void OnPostUpdateNotificationPerfernces(int id)
        {
            if (Notify)
                Massage = "Thank you for turning notifications";
            else
                Massage = "You have turned off email notifications";

            Employee = _employeeRepository.GetEmployee(id);

        }

        private string ProcessUploadFile()
        {
            string uniqueFileName = null;
            if(Photo != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath,"images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    Photo.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
    }
}

RazorPagesGeneral/Pages/Employees/Employees.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesLessons.Models;
using RazorPagesLessons.Services;

namespace RazorPagesGeneral.Pages.Employees
{
    public class EmployeesModel : PageModel
    {
        private readonly IEmployeeRepository _db;

        public EmployeesModel(IEmployeeRepository db)
        {
            _db = db;
                
        }
        public IEnumerable<Employee> Employees { get; set; }

        [BindProperty(SupportsGet =true)]
        public string SearchTerm { get; set; }

        public void OnGet()
        {
            Employees = _db.Search(SearchTerm);
        }
    }
}

RazorPagesGeneral/ViewComponents/HeadCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using RazorPagesLessons.Models;
using RazorPagesLessons.Services;

namespace RazorPagesGeneral.ViewComponents
{
    [ViewComponent(Name = "HeadCount")]
    public class HeadCountViewComponent : ViewComponent
    {
        private readonly IEmployeeRepository _employeeRepository;


        public HeadCountViewComponent(IEmployeeRepository  employeeRepository)
        {
            _employeeRepository = employeeRepository;
        }

        public IViewComponentResult Invoke(Dept? department = null)
        {
            IEnumerable<DeptHeadCount> result = _employeeRepository.EmployeeCountByDept(department);
            return View(result);
        }
    }
}

RazorPagesGeneral/Pages/Employees/Delete.cshtml
@page "{id}"
@model RazorPagesGeneral.Pages.Employees.DeleteModel
@{
    ViewData["Title"] = "Delete";
    ViewData["ShowButtons"] = false;
}

<h1 class="text-center">Delete Confirmational</h1>
<div class="alert alert-danger">
    <div class="row">
        <div class="col-12 col-md-6 col-xl-4 offset-sm-0 offset-md-3 offset-xl-4">
            <partial name="_DisplayEmployeePartial" model="Model.Employee" view-data="ViewData" />
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-6 col-xl-4 offset-sm-0 offset-md-3 offset-xl-4">
            <div class="text-center text-secondary">
                <h4>Employee Id: <span class="text-primary">@Model.Employee.Id</span></h4><hr />
                <h4>Employee Email: <span class="text-primary">@Model.Employee.Email</span></h4><hr />
                <h4>Department: <span class="text-primary">@Model.Employee.Department</span></h4><hr />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <h5>Are you shure whant to delete employee - @Model.Employee.Name?</h5>
            <form method="post">
                <button type="submit" class="btn btn-danger">Yes!</button>
                <a class="btn btn-success" asp-page="/Employees/Employees">No</a>
            </form>
        </div>
    </div>
</div>

RazorPagesGeneral/Pages/Employees/Details.cshtml
@page "{id}"
@model RazorPagesGeneral.Pages.Employees.DetailsModel
@{
    ViewData["Title"] = "Employee Details";
    var photoPath = $"/images/{Model.Employee.PhotoPath ?? "noimage.png"}";
}



<div class="row justify-content-center m-3">
    <div class="col col-lg-8">
        <div class="card cardBoxShadow">
            <div class="card-header cardHeaderStyle text-center">
                <h1>@Model.Employee.Name</h1>
            </div>

            <div class="card-body cardBoxShadow text-center">
                <div class="row">
                    <div class="col col-lg-9">
                        <h4 class="cardTextLeftFloating">Employee Id:@Model.Employee.Id</h4><hr />
                        <h4 class="cardTextLeftFloating">Email:@Model.Employee.Email</h4><hr />
                        <h4 class="cardTextLeftFloating">Department:<span class="text-danger font-weight-bold">@Model.Employee.Department</span></h4><hr />
                    </div>
                    <div class="col col-lg-3">
                        <div style="border-right: 1px solid rgba(0,0,0,.1);">
                            <img class="card-img-top imageThumbnail border border-primary" style="background-color: #540792;" src="@photoPath" asp-append-version="true" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="card-footer text-center" style="background-color: rgba(0,0,0,0.25);">
                            <a asp-page="Employees" class="btn btn-success buttonShadow">Back</a>
                            <a href="#" class="btn btn-primary buttonShadow">Edit</a>
                            <a href="#" class="btn btn-danger buttonShadow">Delete</a>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

@*<div class="row justify-content-center m-3">
    <div class="col col-lg-8">
        @await Component.InvokeAsync("HeadCount", new { department = Model.Employee.Department })
    </div>
</div>*@
<div class="row">
    <div class="col text-center">
       <vc:head-count department="@Model.Employee.Department"></vc:head-count>
    </div>
</div>

RazorPagesGeneral/Pages/Employees/Edit.cshtml
@page "{id:min(1)?}/{handler?}"
@model RazorPagesGeneral.Pages.Employees.EditModel
@{
    var photoPath = $"/images/{Model.Employee.PhotoPath ?? "noimage.png"}";

    var pageTitle = Model.Employee.Id > 0 ? "Edit" : "Create";

    ViewData["Title"] = pageTitle;
}
<form method="post" asp-page-handler="UpdateNotificationPerfernces">
    <div class="row text-center notifyBlock">
        <div class="col form-check">
            <h1>Notification Perference</h1>
            <input asp-for ="Notify" class="form-check-input"/>
            <label asp-for ="Notify" class="form-check-label">
                Receive emaile notification when my details change
            </label><br />
            <button type="submit" class="btn btn-primary text-center">Update Notification Perference</button>

            @if(!string.IsNullOrWhiteSpace(Model.Massage))
            {
                <div class="alert alert-success">
                    <p class="p-3 mt-2">@Model.Massage</p>
                </div>
            }
        </div>

    </div>
    <hr />

</form>

<div asp-validation-summary="ModelOnly" class="text-danger text-center"></div>

    <!--Создаём форму редактирования-->
<form method="post" asp-page-handler="OnPost" class="mt-3" enctype="multipart/form-data">
    <!--Создаём скрытое поле для параметра -->
    <input type="hidden" asp-for="Employee.Id"/>
    <input type="hidden" asp-for="Employee.PhotoPath"/>

    <!--Добавляем поля редактирования-->
    <div class="row justify-content-center m-3">
        <div class="col col-lg-8">
            <div class="card cardBoxShadow">
                <div class="card-header cardHeaderStyle text-center">
                    <!--Добавляем поле редактирования имени-->
                    <div class="form-group row">
                        <label asp-for="Employee.Name" class="col col-lg-4 col-form-label text-right">Edit Name:</label>
                        <div class="col col-lg-6">
                            <input asp-for="Employee.Name" class="form-control" placeholder="@Model.Employee.Name" />
                            <!--Добавляем сообщение валидации формы-->
                            <span asp-validation-for="Employee.Name" class="text-danger"></span>
                        </div>
                    </div>

                </div>
                <div class="card-body cardBodyStyle text-center">
                    <div class="row">
                        <div class="col col-lg-9">
                            <h4 class="cardTextLeftFloating">Employee ID: @Model.Employee.Id</h4><hr />

                            <!--Добавляем поле редактирования e-mail-->
                            <div class="form-group row">
                                <label asp-for="Employee.Email" class="col col-lg-4 col-form-label text-right">Edit E-mail:</label>
                                <div class="col-12 col-lg-6">
                                    <input asp-for="Employee.Email" class="form-control mr-2" placeholder="@Model.Employee.Email" />
                                    <!--Добавляем сообщение валидации формы-->
                                    <span asp-validation-for="Employee.Email" class="text-danger"></span>
                                </div>
                            </div>
                            <hr />
                            <!--Добавляем поле редактирования департамента-->
                            <div class="form-group row">
                                <label asp-for="Employee.Department" class="col col-lg-4 col-form-label text-right">Edit Department:</label>
                                <div class="col-12 col-lg-6">
                                    <!--Создаём выпадающий список с департаментами-->
                                    <!--Необходимо подключить класс локально или глобально-->
                                    <select asp-for="Employee.Department" class="custom-select mr-2" asp-items="Html.GetEnumSelectList<Dept>()">
                                        <!--Добавляем начальный элемент выпадающего списка-->
                                        <option value="">Please Select</option>
                                    </select>
                                    <span asp-validation-for="Employee.Department" class="text-danger"></span>
                                </div>
                            </div>
                            <hr />
                        </div>

                        <div class="col col-lg-3">
                            <div>

                                <img class="card-img-top imageThumbnail border-primary" src="@photoPath" asp-append-version="true" />
                                <div class="custom-file">
                                    <input asp-for="Photo" class="custom-file-input from form-control" />
                                    <label class="custom-file-label text-left">Click here</label>
                                </div>

                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="card-footer text-center" style="background-color: rgba(0, 0, 0, 0.25);">
                                <button type="submit" class="btn btn-success buttonShadow">Update</button>
                                <a asp-page="index" class="btn btn-danger buttonShadow">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @section Scripts{
        <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
            });
        </script>

    <partial name="_ValidationScriptsPartial" />
    }

</form>

RazorPagesGeneral/Pages/Employees/Employees.cshtml
@page
@model RazorPagesGeneral.Pages.Employees.EmployeesModel
@{
    ViewData["Title"] = "Employees";
    ViewData["ShowButtons"] = true;
}

@if (TempData["SuccessMessage"]!= null)
{
<div class="alert alert-success text-center">@TempData["SuccessMessage"]</div>
}

<form method="get" class="mb-3">
    <div class="input-group">
        <input class="form-control" asp-for="SearchTerm" />
        <div class="input-group-append">
            <button type="submit" class="btn btn-primary">Search</button>
        </div>
    </div>
</form>

<vc:head-count department="@null"></vc:head-count>

<h1>Employees</h1>

<div class="row">
    @foreach (var item in Model.Employees)
   {
        <div class="col-12 col-sm-6 col-lg-4">
            <partial name="_DisplayEmployeePartial" model="item" view-data="ViewData" />
        </div>
   }
</div>

  